apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kafka-log-sit
  labels:
    global: \"true\"      
config:
  bootstrap_servers:
  - host: cp-kafka.kafka-namespace.svc.cluster.local
    port: 9092
  keepalive: 60000
  producer_async: true
  producer_async_buffering_limits_messages_in_memory: 50000
  producer_async_flush_timeout: 1000
  producer_request_acks: 1
  producer_request_limits_bytes_per_request: 1.048576e+06
  producer_request_limits_messages_per_request: 200
  producer_request_retries_backoff_timeout: 100
  producer_request_retries_max_attempts: 10
  producer_request_timeout: 2000
  timeout: 10000
  topic: KongLogTopic
plugin: kafka-log
