apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssotoken
  annotations:
    konghq.com/https-redirect-status-code: '302'
    konghq.com/preserve-host: 'false'
    konghq.com/protocols: https
    konghq.com/strip-path: 'true'
spec:
  rules:
  - http:
      paths:
      - path: /api/service/token
        backend:
          serviceName: ssotoken-svc
          servicePort: 8443

apiVersion: v1
kind: Service
metadata:
  name: ssotoken-svc
  annotations:
    konghq.com/override: ssotoken-tokenendpoint
spec:
  type: ExternalName
  externalName: sso-server.com
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443


apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: ssotoken-tokenendpoint
proxy:
  protocol: https
  path: /auth/realms/NaaS/protocol/openid-connect/token
route:
  methods:
    - POST
  
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: oidc-plugin
config:
  client_id:
  - kong-cli
  client_secret:
  - 23434-4234-vdfg34-fsdf-534
  verify_claims: false
  authenticated_groups_claim:
  - clientId
  upstream_headers_claims:
  - clientId
  upstream_headers_names:
  - x-client-id
  issuer: https://sso-server.com/auth/realms/NaaS
  auth_methods:
  - bearer
  hide_credentials: true
  upstream_access_token_header: ' '
plugin: openid-connect
