kind: Service
apiVersion: v1
metadata:
  name: proxy-to-external
spec:
  type: ExternalName
  externalName: www.mocky.io


apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy-from-k8s-to-ext
  annotations:
    konghq.com/strip-path: "true"
	konghq.com/protocols: https
spec:
  rules:
  - http:
      paths:
      - path: /v2/api
        backend:
          serviceName: proxy-to-external
          servicePort: 80


In the API request, use header: -H 'Host:www.mocky.io'

