apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: demo-acl
  annotations:
    kubernetes.io/ingress.class: kong
config:
  whitelist: ['demo-group']
  hide_groups_header: true
plugin: acl
