apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: demo-cli
  namespace: dp-common-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: 'rl-cli1-demo-5'
username: demo-cli
credentials:
  - acl-demo
